version: '3.8'

services:
  web:
    build: .
    container_name: ikar-webserver
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
